include: lint_rules.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - riverpod_lint
  exclude:
    [build/**, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    included_file_warning: ignore
    invalid_annotation_target: ignore
    unused_element_parameter: false
    unrecognized_error_code: ignore

linter:
  rules:
    use_setters_to_change_properties: false
    sort_pub_dependencies: false
    avoid_types_on_closure_parameters: false
    require_trailing_commas: false
    unnecessary_final: false
    omit_local_variable_types: false
    prefer_final_parameters: false
    public_member_api_docs: false
    document_ignores: false
    avoid_classes_with_only_static_members: false
    discarded_futures: false
    diagnostic_describe_all_properties: false
    always_put_control_body_on_new_line: false
    prefer_double_quotes: false
    prefer_relative_imports: false
