// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// REAL CONFIG for the `remind-ai-2555f` Firebase project. These values are
// intentionally PUBLIC client identifiers (web/Android apiKey, appId,
// projectId) — they are not secrets. Access is protected by Firebase App
// Check and Firestore security rules, so this file is safe to commit and is
// required by the Vercel web build. Re-generate with `flutterfire configure`
// if the project ever changes.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Re-run flutterfire configure to add it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMJw1vOeNCHF-RH978w2wUrYT0JWdvrA',
    appId: '1:1088490498640:web:a0c11ea65414fc85a83f55',
    messagingSenderId: '1088490498640',
    projectId: 'remind-ai-2555f',
    authDomain: 'remind-ai-2555f.firebaseapp.com',
    storageBucket: 'remind-ai-2555f.firebasestorage.app',
    measurementId: 'G-R23314FT63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWEJgq4FjIGdfo7jQvrrmX1SnsABke5I',
    appId: '1:1088490498640:android:36c363ac9d979fb2a83f55',
    messagingSenderId: '1088490498640',
    projectId: 'remind-ai-2555f',
    storageBucket: 'remind-ai-2555f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMJw1vOeNCHF-RH978w2wUrYT0JWdvrA',
    appId: '1:1088490498640:web:42e788ef936aa399a83f55',
    messagingSenderId: '1088490498640',
    projectId: 'remind-ai-2555f',
    authDomain: 'remind-ai-2555f.firebaseapp.com',
    storageBucket: 'remind-ai-2555f.firebasestorage.app',
    measurementId: 'G-EMQ2HCVGVQ',
  );
}
