// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:remind_ai/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DreamEntryAdapter());
    registerAdapter(DreamStyleAdapter());
    registerAdapter(ThemeUiModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DreamEntryAdapter());
    registerAdapter(DreamStyleAdapter());
    registerAdapter(ThemeUiModelAdapter());
  }
}
